name: Build KaliLinux Webtop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 登录 GHCR
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 设置版本号（日期+时间）
    - name: Set version
      run: |
        echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    # 构建 base 镜像
    - name: Build base image
      run: |
        BASE_IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/kali-base:${VERSION}
        docker build . --file Dockerfile.base --tag $BASE_IMAGE_TAG
        echo "Built base image: $BASE_IMAGE_TAG"

    # 推送 base 镜像
    - name: Push base image
      run: |
        docker push $BASE_IMAGE_TAG

    # 构建 main 镜像（依赖 GHCR 上的 base）
    - name: Build main image
      run: |
        MAIN_IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/kali:${VERSION}
        docker build . --file Dockerfile --build-arg BASE_IMAGE=$BASE_IMAGE_TAG --tag $MAIN_IMAGE_TAG
        echo "Built main image: $MAIN_IMAGE_TAG"

    # 推送 main 镜像
    - name: Push main image
      run: |
        docker push $MAIN_IMAGE_TAG
