name: Build KaliLinux Webtop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 登录 GHCR
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 设置版本号（日期+时间）
    - name: Set version
      run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    # Build & Push base 镜像
    - name: Build & Push base image
      run: |
        BASE_TAG=ghcr.io/${{ github.repository_owner }}/kali-base:${VERSION}
        BASE_TAG_LATEST=ghcr.io/${{ github.repository_owner }}/kali-base:latest
        docker build . --file Dockerfile.base --tag $BASE_TAG --tag $BASE_TAG_LATEST
        docker push $BASE_TAG
        docker push $BASE_TAG_LATEST

    # Build & Push main 镜像（依赖 base 镜像）
    - name: Build & Push main image
      run: |
        BASE_TAG=ghcr.io/${{ github.repository_owner }}/kali-base:${VERSION}  # CI 每次都是干净环境，确保能拉到 base
        MAIN_TAG=ghcr.io/${{ github.repository_owner }}/kali:${VERSION}
        MAIN_TAG_LATEST=ghcr.io/${{ github.repository_owner }}/kali:latest
        docker build . --file Dockerfile --build-arg BASE_IMAGE=$BASE_TAG --tag $MAIN_TAG --tag $MAIN_TAG_LATEST
        docker push $MAIN_TAG
        docker push $MAIN_TAG_LATEST
